// lib/providers/post_provider.dart

import 'dart:io';
import 'package:flutter/foundation.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:firebase_storage/firebase_storage.dart';
import '../models/posts/post.dart'; 

class PostProvider extends ChangeNotifier {
  final FirebaseFirestore _firestore = FirebaseFirestore.instance;
  final FirebaseStorage _storage = FirebaseStorage.instance;
  final FirebaseAuth _auth = FirebaseAuth.instance;

  // Stream of all posts for the main feed
  Stream<List<Post>> get postsStream {
    return _firestore
        .collection('posts')
        .orderBy('timestamp', descending: true)
        .snapshots()
        .map((snapshot) {
      return snapshot.docs.map((doc) => Post.fromFirestore(doc)).toList();
    });
  }

  // --- Post Creation Logic ---
  Future<void> createPost({
    required String content,
    File? mediaFile,
    DateTime? eventDate,
    String? location,
  }) async {
    final user = _auth.currentUser;
    if (user == null) {
      throw Exception("User not logged in.");
    }

    String? mediaUrl;

    try {
      // 1. Upload Media (if provided)
      if (mediaFile != null) {
        final storageRef = _storage.ref().child('posts/${user.uid}/${DateTime.now().millisecondsSinceEpoch}');
        final uploadTask = storageRef.putFile(mediaFile);
        final snapshot = await uploadTask.whenComplete(() {});
        mediaUrl = await snapshot.ref.getDownloadURL();
      }

      // 2. Create Post Data Map
      final postData = Post(
        id: '', // ID will be generated by Firestore
        userId: user.uid,
        content: content,
        mediaUrl: mediaUrl,
        timestamp: DateTime.now(), // Placeholder, FieldValue.serverTimestamp() is used in toFirestore()
        eventDate: eventDate,
        location: location,
      ).toFirestore();

      // 3. Write to Firestore
      await _firestore.collection('posts').add(postData);

    } catch (e) {
      debugPrint('Error creating post: $e');
      throw Exception('Failed to create post. Please try again.');
    }
  }

  // --- Other post methods (liking, commenting) would go here ---
}