// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1ZI_CkYHKe_EAp5mBxG2DJWYQpxWa_4g',
    appId: '1:1001219178644:web:3d4d59267e7a37796ab481',
    messagingSenderId: '1001219178644',
    projectId: 'ventra-da88e',
    authDomain: 'ventra-da88e.firebaseapp.com',
    storageBucket: 'ventra-da88e.firebasestorage.app',
    measurementId: 'G-P1MYQFNWJG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnNLHLI_IxiIN0wXHh4cvob0osfhbakNE',
    appId: '1:1001219178644:android:2cdf8bf6645f0a356ab481',
    messagingSenderId: '1001219178644',
    projectId: 'ventra-da88e',
    storageBucket: 'ventra-da88e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCz6vc9hnG_KIG04s_SYvTGklxWMQXyL-Y',
    appId: '1:1001219178644:ios:05457842589fdb6b6ab481',
    messagingSenderId: '1001219178644',
    projectId: 'ventra-da88e',
    storageBucket: 'ventra-da88e.firebasestorage.app',
    iosBundleId: 'com.example.ventra',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCz6vc9hnG_KIG04s_SYvTGklxWMQXyL-Y',
    appId: '1:1001219178644:ios:05457842589fdb6b6ab481',
    messagingSenderId: '1001219178644',
    projectId: 'ventra-da88e',
    storageBucket: 'ventra-da88e.firebasestorage.app',
    iosBundleId: 'com.example.ventra',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1ZI_CkYHKe_EAp5mBxG2DJWYQpxWa_4g',
    appId: '1:1001219178644:web:289fa8a51d4bc8dd6ab481',
    messagingSenderId: '1001219178644',
    projectId: 'ventra-da88e',
    authDomain: 'ventra-da88e.firebaseapp.com',
    storageBucket: 'ventra-da88e.firebasestorage.app',
    measurementId: 'G-58KC52HZ18',
  );
}
